package local.skippy.droid.features.widget

import android.app.PendingIntent
import android.appwidget.AppWidgetManager
import android.appwidget.AppWidgetProvider
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.util.Log
import android.widget.RemoteViews
import local.skippy.droid.R

/**
 * SkippyDroid Service Grid Widget — home screen launcher for SkippyTel services.
 *
 * Displays every available service with a UI as a tappable icon.
 * Icons are AI-generated by SkippyTel (SD → Pillow fallback) and fetched
 * on first use, then cached server-side forever.
 *
 * Tap behaviour:
 *  - companionApp set  → launch the Skippy companion Android app
 *  - baseUrl set       → open the service's own web UI in the browser
 *  - neither           → launch SkippyChat with the service id as a hint
 *
 * Update cycle: Android triggers onUpdate() every 5 min (updatePeriodMillis
 * in appwidget-provider XML). The widget also refreshes on app boot via
 * ACTION_APPWIDGET_UPDATE broadcast.
 */
class ServiceGridWidget : AppWidgetProvider() {

    companion object {
        private const val TAG = "ServiceGridWidget"
        const val ACTION_LAUNCH_SERVICE = "local.skippy.droid.ACTION_LAUNCH_SERVICE"

        /** Force all widget instances to refresh their data right now. */
        fun requestUpdate(context: Context) {
            val mgr  = AppWidgetManager.getInstance(context)
            val ids  = mgr.getAppWidgetIds(ComponentName(context, ServiceGridWidget::class.java))
            if (ids.isNotEmpty()) {
                mgr.notifyAppWidgetViewDataChanged(ids, R.id.widget_grid)
            }
        }
    }

    // ── AppWidgetProvider callbacks ────────────────────────────────────────

    override fun onUpdate(
        context: Context,
        appWidgetManager: AppWidgetManager,
        appWidgetIds: IntArray,
    ) {
        Log.i(TAG, "onUpdate: ${appWidgetIds.size} widget(s)")
        appWidgetIds.forEach { id -> updateWidget(context, appWidgetManager, id) }
    }

    override fun onReceive(context: Context, intent: Intent) {
        super.onReceive(context, intent)
        if (intent.action == ACTION_LAUNCH_SERVICE) {
            launchService(context, intent)
        }
    }

    // ── Widget construction ────────────────────────────────────────────────

    private fun updateWidget(
        context: Context,
        mgr: AppWidgetManager,
        appWidgetId: Int,
    ) {
        val views = RemoteViews(context.packageName, R.layout.widget_service_grid)

        // Wire the GridView to our RemoteViewsService
        val serviceIntent = Intent(context, ServiceGridWidgetService::class.java).apply {
            // Unique URI so Android treats each widget instance as distinct
            data = Uri.fromParts("content", appWidgetId.toString(), null)
        }
        views.setRemoteAdapter(R.id.widget_grid, serviceIntent)
        views.setEmptyView(R.id.widget_grid, R.id.widget_empty_text)

        // PendingIntent template — filled in per-item by ServiceGridRemoteViewsFactory
        val launchTemplate = PendingIntent.getBroadcast(
            context,
            appWidgetId,
            Intent(ACTION_LAUNCH_SERVICE).apply { setPackage(context.packageName) },
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_MUTABLE,
        )
        views.setPendingIntentTemplate(R.id.widget_grid, launchTemplate)

        mgr.updateAppWidget(appWidgetId, views)
    }

    // ── Service launch ─────────────────────────────────────────────────────

    private fun launchService(context: Context, intent: Intent) {
        val serviceId    = intent.getStringExtra(ServiceGridRemoteViewsFactory.EXTRA_SERVICE_ID) ?: return
        val companionApp = intent.getStringExtra(ServiceGridRemoteViewsFactory.EXTRA_COMPANION_APP) ?: ""
        val baseUrl      = intent.getStringExtra(ServiceGridRemoteViewsFactory.EXTRA_BASE_URL) ?: ""

        Log.i(TAG, "Launch service: $serviceId  companion=$companionApp  url=$baseUrl")

        val flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP

        when {
            companionApp.isNotBlank() -> {
                // Open our Skippy companion app (SkippyGallery, SkippyChat, etc.)
                context.packageManager.getLaunchIntentForPackage(companionApp)
                    ?.addFlags(flags)
                    ?.let { context.startActivity(it) }
                    ?: Log.w(TAG, "Companion app not installed: $companionApp")
            }

            baseUrl.isNotBlank() -> {
                // Open the service's own web UI directly (Jellyfin, Bilby, etc.)
                context.startActivity(
                    Intent(Intent.ACTION_VIEW, Uri.parse(baseUrl)).addFlags(flags)
                )
            }

            else -> {
                // No app, no URL — open SkippyChat with a hint to activate this service
                context.packageManager.getLaunchIntentForPackage("local.skippy.chat")
                    ?.addFlags(flags)
                    ?.putExtra("activate_service", serviceId)
                    ?.let { context.startActivity(it) }
            }
        }
    }
}
