package local.skippy.droid.layers

import android.Manifest
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.speech.RecognitionListener
import android.speech.RecognizerIntent
import android.speech.SpeechRecognizer
import android.util.Log
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.core.content.ContextCompat

/**
 * Layer 4 — Voice / Input for SkippyDroid.
 *
 * Ported from `apps/SkippyGlassesMac/Sources/VoiceEngine.swift` — this is the
 * Android-native backup STT path, used when the PC MCP (faster-whisper over
 * Tailscale) is unreachable or not yet wired. On the S23 with the Google
 * speech service available offline, commands work without network.
 *
 * ── One-input dispatcher (Session 7 doctrine) ─────────────────────────────
 *   VoiceEngine no longer parses command phrases itself. Every finalized
 *   utterance is forwarded verbatim to [dispatcher] (a [CommandDispatcher]
 *   instance wired by MainActivity). The dispatcher owns the registry of
 *   intents that modules have contributed — so the set of voice commands
 *   is exactly the set of currently-registered intents, automatically in
 *   sync with whichever modules are active.
 *
 *   This is the *fuzzy edge, typed core* seam: raw `String` comes in from
 *   the speech recognizer; the dispatcher classifies it into a typed
 *   [CommandDispatcher.Intent] with structured args for the handler.
 *
 *   To add a new voice command, register an intent on the dispatcher —
 *   do not edit this file.
 *
 * ── Lifecycle model ───────────────────────────────────────────────────────
 *   Android's SpeechRecognizer is single-utterance: after [onResults] or
 *   [onError] the session ends. We chain-restart on every terminal callback
 *   so listening is effectively continuous. A short delay before restart
 *   avoids ERROR_RECOGNIZER_BUSY when the service hasn't released yet.
 *
 * ── Thread model ──────────────────────────────────────────────────────────
 *   SpeechRecognizer MUST be created and called on the main thread. All
 *   methods on [VoiceEngine] assume the caller is on main too — MainActivity
 *   calls [start]/[stop] from onStart()/onStop(), which are main-thread.
 */
class VoiceEngine(private val context: Context) {

    companion object {
        private const val TAG = "Local.Skippy.Voice"

        /** Delay between a recognition session ending and the next one starting.
         *  Short enough to feel continuous, long enough to avoid BUSY errors. */
        private const val RESTART_DELAY_MS = 120L

        /** Max gap after onError we wait before giving up and logging "silent". */
        private const val ERROR_BACKOFF_MS = 400L

        /** Lower bound of Android's loosely-defined onRmsChanged dB range. */
        private const val RMS_DB_FLOOR = -2f

        /** Upper bound of Android's loosely-defined onRmsChanged dB range. */
        private const val RMS_DB_CEIL = 10f
    }

    // ── Public state (Compose-observable) ─────────────────────────────────
    var isListening by mutableStateOf(false)
        private set

    /** Live partial transcript — updates as the Captain speaks. Empty when idle. */
    var partialTranscript by mutableStateOf("")
        private set

    /** Last finalized utterance. Survives across silence for the "heard: …" UI. */
    var lastHeard by mutableStateOf("")
        private set

    /**
     * Normalized microphone RMS amplitude in `[0f, 1f]`, driven by
     * Android's [RecognitionListener.onRmsChanged] callback.
     *
     * Android emits `rmsdB` on a loose scale that is implementation-dependent
     * (commonly ≈[-2, 10]); we clamp-and-normalize to a unit interval here so
     * UI bindings (see [local.skippy.droid.compositor.RmsGlyph]) don't need to
     * know the raw shape.
     *
     * Resets to `0f` on [stop] and whenever the recognizer goes idle (end of
     * speech, between sessions) — so a "silent" glyph means "mic is not
     * currently hearing the Captain," not "mic is off."
     */
    var rmsLevel by mutableStateOf(0f)
        private set

    // ── One-input dispatcher (Session 7) ──────────────────────────────────
    /**
     * The single choke-point for finalized utterances. MainActivity wires
     * this after constructing both [VoiceEngine] and the dispatcher;
     * nothing happens if it's left null (useful for tests and for voice
     * running before the dispatcher is ready).
     *
     * Every finalized transcript in [handleTranscript] is forwarded here
     * with [CommandDispatcher.Source.VOICE]. Intent registration lives
     * entirely on the dispatcher — this class is source-agnostic.
     */
    var dispatcher: CommandDispatcher? = null

    // ── Private ───────────────────────────────────────────────────────────
    private val main = Handler(Looper.getMainLooper())
    private var recognizer: SpeechRecognizer? = null

    /** True once [start] has been called; used so auto-restart stops on [stop]. */
    private var running = false

    /** True while a recognition session is in flight (between startListening and
     *  onResults/onError). Guards against double-start. */
    private var sessionActive = false

    // ── Lifecycle ─────────────────────────────────────────────────────────

    fun start() {
        if (running) return
        if (ContextCompat.checkSelfPermission(context, Manifest.permission.RECORD_AUDIO)
                != PackageManager.PERMISSION_GRANTED) {
            Log.w(TAG, "start(): RECORD_AUDIO not granted — aborting")
            return
        }
        if (!SpeechRecognizer.isRecognitionAvailable(context)) {
            Log.w(TAG, "start(): SpeechRecognizer not available on this device")
            return
        }

        running = true
        createRecognizer()
        beginSession()
        isListening = true
        Log.d(TAG, "VoiceEngine started")
    }

    fun stop() {
        running = false
        isListening = false
        sessionActive = false
        main.removeCallbacksAndMessages(null)
        recognizer?.let {
            try { it.cancel() } catch (_: Throwable) {}
            try { it.destroy() } catch (_: Throwable) {}
        }
        recognizer = null
        partialTranscript = ""
        rmsLevel = 0f
        Log.d(TAG, "VoiceEngine stopped")
    }

    // ── Recognition session plumbing ──────────────────────────────────────

    private fun createRecognizer() {
        // Prefer the on-device recognizer on API 31+ so we don't round-trip
        // through Google's cloud for every utterance. Falls back automatically.
        recognizer = if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S) {
            SpeechRecognizer.createOnDeviceSpeechRecognizer(context)
                ?: SpeechRecognizer.createSpeechRecognizer(context)
        } else {
            SpeechRecognizer.createSpeechRecognizer(context)
        }
        recognizer?.setRecognitionListener(listener)
    }

    private fun beginSession() {
        if (!running || sessionActive) return
        val r = recognizer ?: return

        val intent = Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH).apply {
            putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL, RecognizerIntent.LANGUAGE_MODEL_FREE_FORM)
            putExtra(RecognizerIntent.EXTRA_LANGUAGE, "en-US")
            putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS, true)
            putExtra(RecognizerIntent.EXTRA_MAX_RESULTS, 1)
            // API 31+: prefer running on-device so we don't depend on Skippy Tel being reachable.
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S) {
                putExtra(RecognizerIntent.EXTRA_PREFER_OFFLINE, true)
            }
        }
        sessionActive = true
        try {
            r.startListening(intent)
        } catch (t: Throwable) {
            Log.w(TAG, "startListening threw: ${t.message}")
            sessionActive = false
            scheduleRestart(ERROR_BACKOFF_MS)
        }
    }

    /** Schedule the next recognition session. Safe to call from any callback. */
    private fun scheduleRestart(delayMs: Long = RESTART_DELAY_MS) {
        if (!running) return
        main.postDelayed({
            if (!running) return@postDelayed
            sessionActive = false
            beginSession()
        }, delayMs)
    }

    // ── RecognitionListener ───────────────────────────────────────────────

    private val listener = object : RecognitionListener {

        override fun onReadyForSpeech(params: Bundle?) {
            // Mic is hot — show "listening…" by clearing any stale partial.
            partialTranscript = ""
        }

        override fun onBeginningOfSpeech() {}

        override fun onRmsChanged(rmsdB: Float) {
            // Android's rmsdB is loosely in [-2, 10] (implementation-dependent).
            // Normalize to [0, 1] for UI consumers that expect a unit interval.
            rmsLevel = ((rmsdB - RMS_DB_FLOOR) / (RMS_DB_CEIL - RMS_DB_FLOOR))
                .coerceIn(0f, 1f)
        }

        override fun onBufferReceived(buffer: ByteArray?) {}

        override fun onEndOfSpeech() {
            // Captain stopped talking; results will arrive shortly via onResults.
            // Drop rmsLevel to 0 so the RmsGlyph fades while we wait for the
            // transcript — otherwise the last sampled RMS stays visible and
            // the glyph looks "stuck" between the end of speech and onResults.
            rmsLevel = 0f
        }

        override fun onError(error: Int) {
            // Noisy "no speech detected" errors are part of normal operation when
            // the Captain hasn't spoken — don't log those at WARN level.
            val msg = errorName(error)
            val quiet = error == SpeechRecognizer.ERROR_NO_MATCH ||
                        error == SpeechRecognizer.ERROR_SPEECH_TIMEOUT
            if (quiet) Log.v(TAG, "onError: $msg") else Log.w(TAG, "onError: $msg")

            // Permissions / client errors can't be recovered without user action.
            if (error == SpeechRecognizer.ERROR_INSUFFICIENT_PERMISSIONS) {
                running = false
                isListening = false
                return
            }
            partialTranscript = ""
            scheduleRestart(if (quiet) RESTART_DELAY_MS else ERROR_BACKOFF_MS)
        }

        override fun onPartialResults(partialResults: Bundle?) {
            val text = firstResult(partialResults) ?: return
            partialTranscript = text
        }

        override fun onResults(results: Bundle?) {
            val text = firstResult(results) ?: ""
            partialTranscript = ""
            if (text.isNotBlank()) {
                handleTranscript(text)
            }
            scheduleRestart()
        }

        override fun onEvent(eventType: Int, params: Bundle?) {}
    }

    // ── Transcript forwarding ─────────────────────────────────────────────

    /**
     * Forward a finalized utterance to the [CommandDispatcher]. This engine
     * does no phrase matching itself — the dispatcher owns the registry and
     * returns a typed [CommandDispatcher.DispatchResult] (unused here; the
     * intent handlers have already been invoked by the time this returns).
     *
     * Normalization (`lowercase().trim()`) is also performed inside
     * [CommandDispatcher.dispatch], but we do it here first so [lastHeard]
     * shows the form we forwarded.
     */
    private fun handleTranscript(raw: String) {
        val text = raw.lowercase().trim()
        if (text.isEmpty()) return

        lastHeard = text
        Log.d(TAG, "heard: $text")

        val d = dispatcher
        if (d == null) {
            Log.v(TAG, "no dispatcher wired — dropping: $text")
            return
        }
        d.dispatch(text, CommandDispatcher.Source.VOICE)
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private fun firstResult(bundle: Bundle?): String? {
        val list = bundle?.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION)
        return list?.firstOrNull()
    }

    private fun errorName(code: Int): String = when (code) {
        SpeechRecognizer.ERROR_AUDIO                  -> "AUDIO"
        SpeechRecognizer.ERROR_CLIENT                 -> "CLIENT"
        SpeechRecognizer.ERROR_INSUFFICIENT_PERMISSIONS -> "INSUFFICIENT_PERMISSIONS"
        SpeechRecognizer.ERROR_NETWORK                -> "NETWORK"
        SpeechRecognizer.ERROR_NETWORK_TIMEOUT        -> "NETWORK_TIMEOUT"
        SpeechRecognizer.ERROR_NO_MATCH               -> "NO_MATCH"
        SpeechRecognizer.ERROR_RECOGNIZER_BUSY        -> "RECOGNIZER_BUSY"
        SpeechRecognizer.ERROR_SERVER                 -> "SERVER"
        SpeechRecognizer.ERROR_SPEECH_TIMEOUT         -> "SPEECH_TIMEOUT"
        else                                           -> "UNKNOWN($code)"
    }
}
